from createGraphs import createGraphs
from convertSPMF import convertSPMF
from calculateMeasures import calculateMeasures


#Download the OCEL file and save it in the OCEL folder.
path = " "

createGraphs(path)

outputFileName = "SPMFToolInput"

#The output files are saved in the temp folder
convertSPMF(path,outputFileName)

'''
    In this stage of the code, it is necessary to use the 
    input and output of the SPMF tool, keeping in mind that 
    the SPMF tool is not yet in the code. Therefore, it is necessary to 
    download it from (https://www.philippe-fournier-viger.com/spmf/).
'''

SPMFInputPath = "temp/SPMFToolInput.txt"
SPMFOutputPath = " " # path of the rules file generated by the SPMF tool
calculateMeasures(SPMFInputPath,SPMFOutputPath)



